[package]
name = "image_base64_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
image = "0.23.14"
regex = "1.5.4"
rustc-serialize = "0.3.24"
